repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
        exclude: src/controlservice/
      - id: end-of-file-fixer
        exclude: src/controlservice/
      - id: trailing-whitespace
        exclude: src/controlservice/
      - id: check-yaml # checks for correct yaml syntax for github actions ex.
        exclude: src/controlservice/
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.290
    hooks:
      - id: ruff
        exclude: src/controlservice/
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        exclude: src/controlservice/
