version: '3.8'

services:

  training_api:
    build: ./src/trainingservice
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    env_file:
      - .env

  training_worker:
    build: ./src/trainingservice
    command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log -Q ${RABBITMQ_TRAIN_QUEUE}
    env_file:
      - .env
    depends_on:
      - training_api

  dashboard:
    build: ./src/dashboardservice
    command: celery --broker=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT} flower --port=5555
    ports:
      - 5556:5555
    env_file:
      - .env
    depends_on:
      - training_api
      - training_worker
