version: '3.8'

services:

  # control_api:
  #   build: ./src/controlservice
  #   ports:
  #     - "8000:8000"
  #   command: uvicorn main:app --host 0.0.0.0 --reload
  #   volumes:
  #     - ./src/controlservice:/media/train_videos/
  #   env_file:
  #     - .env

  training_worker:
    build: ./src/trainingservice
    command: python3 training_worker.py
    runtime: nvidia
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_TRAIN_QUEUE=${RABBITMQ_TRAIN_QUEUE}
      - RABBITMQ_TEST_QUEUE=${RABBITMQ_TEST_QUEUE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${DATA_DIR}:/data

  dataset_worker:
    build: ./src/datasetservice
    command: python dataset_worker.py
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DATA_QUEUE=${RABBITMQ_DATA_QUEUE}
      - RABBITMQ_TEST_QUEUE=${RABBITMQ_TEST_QUEUE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${DATA_DIR}:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data
