version: '3.8'

services:

  # training_api:
  #   build: ./src/trainingservice
  #   ports:
  #     - 8004:8000
  #   command: uvicorn main:app --host 0.0.0.0 --reload
  #   env_file:
  #     - .env

  # training_worker:
  #   build: ./src/trainingservice
  #   command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log -Q ${RABBITMQ_TRAIN_QUEUE}
  #   env_file:
  #     - .env
  #   depends_on:
  #     - training_api

  # control_api:
  #   build: ./src/controlservice
  #   ports:
  #     - "8000:8000"
  #   command: uvicorn main:app --host 0.0.0.0 --reload
  #   volumes:
  #     - ./src/controlservice:/media/train_videos/
  #   env_file:
  #     - .env

  dataset_worker:
    build: ./src/datasetservice
    command: python dataset_worker.py
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_TEST_QUEUE=${RABBITMQ_TEST_QUEUE}
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
